import { mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { toSlug } from "./slug.ts";
import * as templates from "./templates.ts";
import type { TemplateContext } from "./templates.ts";

export const DEFAULT_CORE_VERSION = "workspace:*";

export interface BuildFilesOptions {
  appName: string;
  coreVersion?: string;
}

export interface GenerateAppOptions extends BuildFilesOptions {
  targetDir: string;
  dryRun?: boolean;
  force?: boolean;
}

export interface GeneratedFile {
  path: string;
  contents: string;
}

export interface GenerateAppResult {
  files: GeneratedFile[];
  context: TemplateContext;
}

const toContext = (options: BuildFilesOptions): TemplateContext => ({
  appName: options.appName,
  slug: toSlug(options.appName),
  coreVersion: options.coreVersion ?? DEFAULT_CORE_VERSION,
});

const genericSourceFile = (path: string): string =>
  readFileSync(new URL(`../../../${path}`, import.meta.url), "utf8");

/**
 * Builds a generated app from the canonical generic fixtures. Only the small
 * app configuration and package metadata are rendered here; chat behavior is
 * copied verbatim from the fixture source.
 */
export const buildGeneratedFiles = (options: BuildFilesOptions): GeneratedFile[] => {
  const context = toContext(options);
  return [
    { path: "README.md", contents: templates.readme(context) },
    { path: ".env.example", contents: templates.envExample() },
    { path: ".gitignore", contents: templates.gitignore() },
    { path: "web/package.json", contents: templates.webPackageJson(context) },
    { path: "web/index.html", contents: templates.webIndexHtml(context) },
    { path: "web/public/manifest.webmanifest", contents: templates.webManifest(context) },
    {
      path: "web/public/service-worker.js",
      contents: genericSourceFile("apps/generic-web/public/service-worker.js"),
    },
    {
      path: "web/public/icon.svg",
      contents: genericSourceFile("apps/generic-web/public/icon.svg"),
    },
    {
      path: "web/vite-env.d.ts",
      contents: genericSourceFile("apps/generic-web/vite-env.d.ts"),
    },
    { path: "web/vite.config.ts", contents: genericSourceFile("apps/generic-web/vite.config.ts") },
    { path: "web/tsconfig.json", contents: genericSourceFile("apps/generic-web/tsconfig.json") },
    { path: "web/src/app-config.ts", contents: templates.webAppConfig(context) },
    { path: "web/src/app.css", contents: genericSourceFile("apps/generic-web/src/app.css") },
    { path: "web/src/app.tsx", contents: genericSourceFile("apps/generic-web/src/app.tsx") },
    {
      path: "web/src/chat-session.ts",
      contents: genericSourceFile("apps/generic-web/src/chat-session.ts"),
    },
    {
      path: "web/src/chat-settings.ts",
      contents: genericSourceFile("apps/generic-web/src/chat-settings.ts"),
    },
    {
      path: "web/src/conversation-client.ts",
      contents: genericSourceFile("apps/generic-web/src/conversation-client.ts"),
    },
    { path: "web/src/main.tsx", contents: genericSourceFile("apps/generic-web/src/main.tsx") },
    { path: "worker/package.json", contents: templates.workerPackageJson(context) },
    {
      path: "worker/alchemy.run.ts",
      contents: genericSourceFile("apps/generic-worker/alchemy.run.ts"),
    },
    {
      path: "worker/drizzle.config.ts",
      contents: genericSourceFile("apps/generic-worker/drizzle.config.ts"),
    },
    {
      path: "worker/tsconfig.json",
      contents: genericSourceFile("apps/generic-worker/tsconfig.json"),
    },
    { path: "worker/src/app-config.ts", contents: templates.workerAppConfig(context) },
    {
      path: "worker/src/db/schema.ts",
      contents: genericSourceFile("apps/generic-worker/src/db/schema.ts"),
    },
    {
      path: "worker/src/generic.worker.ts",
      contents: genericSourceFile("apps/generic-worker/src/generic.worker.ts"),
    },
    { path: "worker/migrations/.gitkeep", contents: "" },
  ];
};

const assertTargetIsWritable = async (targetDir: string, force: boolean): Promise<void> => {
  if (!existsSync(targetDir)) return;
  const existing = await readdir(targetDir);
  if (existing.length > 0 && !force) {
    throw new Error(`Target directory "${targetDir}" is not empty. Pass force to overwrite.`);
  }
};

/**
 * Writes the composition-root files generated by `buildGeneratedFiles` into
 * `targetDir`. Never reads from or copies core package source directories —
 * every generated file only references those packages by name.
 */
export const generateApp = async (options: GenerateAppOptions): Promise<GenerateAppResult> => {
  const context = toContext(options);
  const files = buildGeneratedFiles(options);
  if (options.dryRun === true) return { files, context };

  await assertTargetIsWritable(options.targetDir, options.force === true);
  await Promise.all(
    files.map(async (file) => {
      const fullPath = join(options.targetDir, ...file.path.split("/"));
      await mkdir(dirname(fullPath), { recursive: true });
      await writeFile(fullPath, file.contents);
    }),
  );
  return { files, context };
};
