import { mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";

import { toSlug } from "./slug.ts";
import * as templates from "./templates.ts";
import type { TemplateContext } from "./templates.ts";

export const DEFAULT_CORE_VERSION = "workspace:*";

export interface BuildFilesOptions {
  appName: string;
  coreVersion?: string;
}

export interface GenerateAppOptions extends BuildFilesOptions {
  targetDir: string;
  dryRun?: boolean;
  force?: boolean;
}

export interface GeneratedFile {
  path: string;
  contents: string;
}

export interface GenerateAppResult {
  files: GeneratedFile[];
  context: TemplateContext;
}

const toContext = (options: BuildFilesOptions): TemplateContext => ({
  appName: options.appName,
  slug: toSlug(options.appName),
  coreVersion: options.coreVersion ?? DEFAULT_CORE_VERSION,
});

/**
 * Pure file-set builder. No filesystem access, so callers can assert on
 * exact output (path list, package.json contents) without touching disk.
 */
export const buildGeneratedFiles = (options: BuildFilesOptions): GeneratedFile[] => {
  const context = toContext(options);
  return [
    { path: "README.md", contents: templates.readme(context) },
    { path: ".env.example", contents: templates.envExample() },
    { path: ".gitignore", contents: templates.gitignore() },
    { path: "web/package.json", contents: templates.webPackageJson(context) },
    { path: "web/index.html", contents: templates.webIndexHtml(context) },
    { path: "web/vite-env.d.ts", contents: templates.webViteEnvDts() },
    { path: "web/vite.config.ts", contents: templates.webViteConfig() },
    { path: "web/tsconfig.json", contents: templates.webTsconfig() },
    { path: "web/src/app.tsx", contents: templates.webAppTsx(context) },
    { path: "web/src/main.tsx", contents: templates.webMainTsx() },
    { path: "worker/package.json", contents: templates.workerPackageJson(context) },
    { path: "worker/alchemy.run.ts", contents: templates.workerAlchemyRun(context) },
    { path: "worker/drizzle.config.ts", contents: templates.workerDrizzleConfig() },
    { path: "worker/tsconfig.json", contents: templates.workerTsconfig() },
    { path: "worker/src/db/schema.ts", contents: templates.workerSchema() },
    { path: "worker/src/app.worker.ts", contents: templates.workerAppWorker(context) },
    { path: "worker/migrations/.gitkeep", contents: "" },
  ];
};

const assertTargetIsWritable = async (targetDir: string, force: boolean): Promise<void> => {
  if (!existsSync(targetDir)) return;
  const existing = await readdir(targetDir);
  if (existing.length > 0 && !force) {
    throw new Error(`Target directory "${targetDir}" is not empty. Pass force to overwrite.`);
  }
};

/**
 * Writes the composition-root files generated by `buildGeneratedFiles` into
 * `targetDir`. Never reads from or copies core package source directories —
 * every generated file only references those packages by name.
 */
export const generateApp = async (options: GenerateAppOptions): Promise<GenerateAppResult> => {
  const context = toContext(options);
  const files = buildGeneratedFiles(options);
  if (options.dryRun === true) return { files, context };

  await assertTargetIsWritable(options.targetDir, options.force === true);
  await Promise.all(
    files.map(async (file) => {
      const fullPath = join(options.targetDir, ...file.path.split("/"));
      await mkdir(dirname(fullPath), { recursive: true });
      await writeFile(fullPath, file.contents);
    }),
  );
  return { files, context };
};
