export interface TemplateContext {
  appName: string;
  slug: string;
  coreVersion: string;
}

const webPackageName = (context: TemplateContext): string => `${context.slug}-web`;
const workerPackageName = (context: TemplateContext): string => `${context.slug}-worker`;

export const readme = (context: TemplateContext): string =>
  `# ${context.appName}

A thin composition root generated by \`@emi/create-chat-app\`. Application logic — conversations,
messages, branches, resumable generation, memory, notes, and the chat shell UI — lives entirely in
released/workspace core packages:

- \`@emi/core/contract\` — schemas and API contracts
- \`@emi/core/server\` — auth, conversations, branches, generation, memory, notes
- \`@emi/core/web\` — chat shell, composer, sidebar, settings
- \`@emi/core/cloudflare\` — D1, R2, Durable Object, Worker, and Alchemy adapters

Nothing under \`web/\` or \`worker/\` in this generated tree is a copy of core package source. Both
sub-packages only import the packages above by name (currently pinned to \`${context.coreVersion}\`).
Upgrading is a normal dependency bump in \`web/package.json\` and \`worker/package.json\`, not a manual
port.

## Layout

\`\`\`text
web/       Vite + React composition root depending on @emi/core/web + @emi/core/contract
worker/    Alchemy Cloudflare Worker composition root depending on @emi/core/server + @emi/core/cloudflare
\`\`\`

## Getting started

Add \`web\` and \`worker\` to a pnpm workspace that also resolves the \`@emi/core\` packages (this
repository's root workspace already does, if this directory was generated under \`apps/\`). Then:

\`\`\`bash
pnpm install
pnpm --filter ${webPackageName(context)} typecheck
pnpm --filter ${workerPackageName(context)} typecheck
pnpm --filter ${workerPackageName(context)} db:generate
pnpm --filter ${webPackageName(context)} dev
pnpm --filter ${workerPackageName(context)} dev
\`\`\`

A product flavor adds nav, pages, tools, and prompt fragments by passing \`CoreWebContributions\` to
\`CoreWebProvider\` (web) and by merging an \`AppDefinition\` with \`coreAppDefinition\` (worker) — see
\`apps/generic-web\` and \`apps/generic-worker\` in the upstream monorepo for a worked example.

## Deferred

Real npm publishing of the \`@emi/core\` package is deferred; until then, the generated
dependency version (\`${context.coreVersion}\`) only resolves inside a pnpm workspace that also
contains that package as a member.
`;

export const envExample = (): string =>
  `# Copy to .env and fill in secrets for session auth.
# Required for the worker:
#   BETTER_AUTH_SECRET   (min 32 chars)
#   BETTER_AUTH_URL      (public origin, e.g. http://localhost:8787)
# Optional local smoke only (never in production):
#   ALLOW_DEMO_USER_HEADER=1   then send x-demo-user-id on API calls
# Optional branding:
#   AUTH_APP_NAME=Core Chat
`;

export const gitignore = (): string =>
  `node_modules
dist
.alchemy
.wrangler
data
.env
.env.*
!.env.example
`;

export const webPackageJson = (context: TemplateContext): string =>
  `{
  "name": "${webPackageName(context)}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --port 3233",
    "build": "vite build",
    "typecheck": "tsc --noEmit",
    "start": "vite preview --port 3233",
    "format": "oxfmt --check",
    "format:fix": "oxfmt",
    "lint": "oxlint && oxfmt --check",
    "lint:fix": "oxlint --fix && oxfmt"
  },
  "dependencies": {
    "@emi/core": "${context.coreVersion}",
    "ai": "catalog:",
    "effect": "catalog:",
    "react": "^19.2.7",
    "react-dom": "^19.2.7"
  },
  "devDependencies": {
    "@types/node": "^26.0.0",
    "@types/react": "^19.2.17",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^6.0.3",
    "oxfmt": "catalog:",
    "oxlint": "catalog:",
    "typescript": "catalog:",
    "vite": "^8.1.4"
  }
}
`;

export const webIndexHtml = (context: TemplateContext): string =>
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${context.appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

export const webViteEnvDts = (): string => `/// <reference types="vite/client" />\n`;

export const webViteConfig = (): string =>
  `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: "dist",
  },
});
`;

export const webTsconfig = (): string =>
  `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "types": ["node"]
  },
  "include": ["vite-env.d.ts", "src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules"]
}
`;

export const webAppTsx = (context: TemplateContext): string =>
  `import {
  convertFileListToFileUIParts,
  DefaultChatTransport,
  readUIMessageStream,
  type FileUIPart,
  type UIMessage,
} from "ai";
import { type FormEvent, useEffect, useRef, useState } from "react";
import "./app.css";
import { defaultChatSettings, readChatSettings, type ChatSettings } from "./chat-settings.ts";
import {
  cloneConversation,
  deleteConversation,
  listConversations,
  loadConversation,
  updateConversation,
  type Conversation,
} from "./conversation-client.ts";

const appName = ${JSON.stringify(context.appName)};
const settingsStorageKey = "chat-settings";
const textFrom = (message: UIMessage): string =>
  message.parts.flatMap((part) => (part.type === "text" ? [part.text] : [])).join("\\n");

const replaceMessage = (messages: UIMessage[], message: UIMessage): UIMessage[] => {
  const index = messages.findIndex((candidate) => candidate.id === message.id);
  if (index < 0) return [...messages, message];
  return [...messages.slice(0, index), message, ...messages.slice(index + 1)];
};

export const App = () => {
  const abortController = useRef<AbortController | undefined>(undefined);
  const composerForm = useRef<HTMLFormElement | null>(null);
  const streamOperation = useRef(0);
  const [settings, setSettings] = useState<ChatSettings>(defaultChatSettings);
  const [messages, setMessages] = useState<UIMessage[]>([]);
  const [draft, setDraft] = useState("");
  const [conversationId, setConversationId] = useState<string>();
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [conversationSearch, setConversationSearch] = useState("");
  const [queuedFollowUps, setQueuedFollowUps] = useState<Array<{ id: string; text: string; files: FileUIPart[] }>>([]);
  const [files, setFiles] = useState<FileUIPart[]>([]);
  const [temporary, setTemporary] = useState(false);
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState<string>();

  useEffect(() => setSettings(readChatSettings({ storageKey: settingsStorageKey })), []);
  useEffect(() => localStorage.setItem(settingsStorageKey, JSON.stringify(settings)), [settings]);

  const refreshConversations = async ({ search }: { search: string }) => {
    try {
      setConversations(await listConversations({ search }));
    } catch {
      setConversations([]);
    }
  };

  useEffect(() => {
    void refreshConversations({ search: "" });
  }, []);

  const startFresh = () => {
    streamOperation.current += 1;
    abortController.current?.abort();
    abortController.current = undefined;
    setConversationId(undefined);
    setMessages([]);
    setDraft("");
    setError(undefined);
    setStreaming(false);
    setQueuedFollowUps([]);
    setFiles([]);
  };

  const consumeStream = async ({ operation, stream }: { operation: number; stream: ReadableStream<Parameters<typeof readUIMessageStream>[0]["stream"] extends ReadableStream<infer Chunk> ? Chunk : never> }) => {
    for await (const streamedMessage of readUIMessageStream({ stream, terminateOnError: true })) {
      if (operation !== streamOperation.current) return;
      setMessages((current) => replaceMessage(current, streamedMessage));
    }
  };

  const resumeConversation = async ({ id }: { id: string }) => {
    const operation = streamOperation.current + 1;
    streamOperation.current = operation;
    setStreaming(true);
    try {
      const transport = new DefaultChatTransport<UIMessage>({ api: (import.meta.env.VITE_API_ORIGIN ?? "") + "/api/chat" });
      const stream = await transport.reconnectToStream({ chatId: id });
      if (stream === null) return;
      await consumeStream({ operation, stream });
    } catch {
      if (operation === streamOperation.current) setError("Unable to resume this conversation.");
    } finally {
      if (operation === streamOperation.current) setStreaming(false);
    }
  };

  const openConversation = async ({ id }: { id: string }) => {
    try {
      const loaded = await loadConversation({ conversationId: id });
      setConversationId(loaded.conversation.id);
      setMessages(loaded.messages);
      setTemporary(false);
      setError(undefined);
      void resumeConversation({ id });
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Unable to load this conversation.");
    }
  };

  const updateConversationAction = async ({ id, patch }: { id: string; patch: { title?: string; status?: "regular" | "archived"; pinned?: boolean } }) => {
    try {
      const updated = await updateConversation({ conversationId: id, patch });
      setConversations((current) => current.map((conversation) => conversation.id === updated.id ? updated : conversation));
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Unable to update this conversation.");
    }
  };

  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const text = draft.trim();
    if (text === "" && files.length === 0) return;
    if (streaming) {
      setQueuedFollowUps((current) => [...current, { id: crypto.randomUUID(), text, files }]);
      setDraft("");
      setFiles([]);
      return;
    }
    if (settings.apiKey.trim() === "") {
      setError("Add an API key in settings before sending a message.");
      return;
    }

    const userMessage: UIMessage = {
      id: crypto.randomUUID(),
      role: "user",
      parts: [{ type: "text", text }, ...files],
    };
    const nextMessages = [...messages, userMessage];
    const controller = new AbortController();
    const operation = streamOperation.current + 1;
    streamOperation.current = operation;
    abortController.current = controller;
    setMessages(nextMessages);
    setDraft("");
    setFiles([]);
    setError(undefined);
    setStreaming(true);

    try {
      const transport = new DefaultChatTransport<UIMessage>({
        api: (import.meta.env.VITE_API_ORIGIN ?? "") + "/api/chat",
        fetch: async (input, init) => {
          const response = await fetch(input, init);
          const returnedConversationId = response.headers.get("x-conversation-id");
          if (returnedConversationId !== null) {
            setConversationId(returnedConversationId);
            void refreshConversations({ search: conversationSearch });
          }
          return response;
        },
      });
      const stream = await transport.sendMessages({
        trigger: "submit-message",
        chatId: conversationId ?? userMessage.id,
        messageId: userMessage.id,
        messages: nextMessages,
        abortSignal: controller.signal,
        body: {
          sessionId: conversationId,
          temporary,
          system: settings.systemPrompt === "" ? undefined : settings.systemPrompt,
          config: {
            provider: settings.provider,
            apiKey: settings.apiKey,
            ...(settings.baseUrl === "" ? {} : { baseUrl: settings.baseUrl }),
            model: settings.model,
          },
          title: {
            ...(settings.titleModel === "" ? {} : { model: settings.titleModel }),
            ...(settings.titlePrompt === "" ? {} : { prompt: settings.titlePrompt }),
          },
        },
      });
      await consumeStream({ operation, stream });
    } catch (cause) {
      if (controller.signal.aborted || operation !== streamOperation.current) return;
      setError(cause instanceof Error ? cause.message : "Unable to complete this chat request.");
    } finally {
      if (abortController.current === controller) abortController.current = undefined;
      if (operation === streamOperation.current) setStreaming(false);
    }
  };

  const forceSendQueued = ({ id }: { id: string }) => {
    const queued = queuedFollowUps.find((item) => item.id === id);
    if (queued === undefined) return;
    streamOperation.current += 1;
    abortController.current?.abort();
    abortController.current = undefined;
    setQueuedFollowUps((current) => current.filter((item) => item.id !== id));
    setDraft(queued.text);
    setFiles(queued.files);
    setStreaming(false);
    setTimeout(() => composerForm.current?.requestSubmit());
  };

  return (
    <main className="chat-app">
      <aside className="settings-panel">
        <div>
          <p className="eyebrow">CHAT STARTER</p>
          <h1>{appName}</h1>
          <p className="muted">Your provider key stays in this browser.</p>
        </div>
        <button className="secondary-button" onClick={startFresh} type="button">New chat</button>
        <label>Search conversations<input onChange={(event) => { const search = event.target.value; setConversationSearch(search); void refreshConversations({ search }); }} placeholder="Search chats" value={conversationSearch} /></label>
        <div className="conversation-list">
          {conversations.map((conversation) => (
            <article className={conversation.id === conversationId ? "conversation active" : "conversation"} key={conversation.id}>
              <button onClick={() => void openConversation({ id: conversation.id })} type="button">{conversation.title || "New chat"}</button>
              <div className="conversation-actions">
                <button aria-label={conversation.pinned ? "Unpin conversation" : "Pin conversation"} onClick={() => void updateConversationAction({ id: conversation.id, patch: { pinned: !conversation.pinned } })} type="button">{conversation.pinned ? "Unpin" : "Pin"}</button>
                <button aria-label="Rename conversation" onClick={() => { const title = window.prompt("Conversation name", conversation.title ?? ""); if (title === null || title.trim() === "") return; void updateConversationAction({ id: conversation.id, patch: { title: title.trim() } }); }} type="button">Rename</button>
                <button aria-label="Clone conversation" onClick={() => void cloneConversation({ conversationId: conversation.id }).then((cloned) => { setConversations((current) => [cloned, ...current]); void openConversation({ id: cloned.id }); }).catch(() => setError("Unable to clone this conversation."))} type="button">Clone</button>
                <button aria-label="Archive conversation" onClick={() => void updateConversationAction({ id: conversation.id, patch: { status: conversation.status === "regular" ? "archived" : "regular" } })} type="button">{conversation.status === "regular" ? "Archive" : "Restore"}</button>
                <button aria-label="Delete conversation" onClick={() => { if (!window.confirm("Delete this conversation permanently?")) return; void deleteConversation({ conversationId: conversation.id }).then(() => { setConversations((current) => current.filter((item) => item.id !== conversation.id)); if (conversation.id === conversationId) startFresh(); }).catch(() => setError("Unable to delete this conversation.")); }} type="button">Delete</button>
              </div>
            </article>
          ))}
        </div>
        <label>API key<input autoComplete="off" onChange={(event) => setSettings((current) => ({ ...current, apiKey: event.target.value }))} placeholder="sk-..." type="password" value={settings.apiKey} /></label>
        <label>Provider base URL<input onChange={(event) => setSettings((current) => ({ ...current, baseUrl: event.target.value }))} placeholder="https://api.openai.com/v1" value={settings.baseUrl} /></label>
        <label>Default model<input onChange={(event) => setSettings((current) => ({ ...current, model: event.target.value }))} placeholder="gpt-4o-mini" value={settings.model} /></label>
        <label>Default system prompt<textarea onChange={(event) => setSettings((current) => ({ ...current, systemPrompt: event.target.value }))} placeholder="Optional instructions for every answer" rows={3} value={settings.systemPrompt} /></label>
        <label>Title model<input onChange={(event) => setSettings((current) => ({ ...current, titleModel: event.target.value }))} placeholder="gpt-4o-mini" value={settings.titleModel} /></label>
        <label>Title prompt<textarea onChange={(event) => setSettings((current) => ({ ...current, titlePrompt: event.target.value }))} placeholder="Optional instructions for automatic conversation titles" rows={2} value={settings.titlePrompt} /></label>
        <label className="toggle"><input checked={temporary} onChange={(event) => { setTemporary(event.target.checked); startFresh(); }} type="checkbox" />Temporary chat</label>
        <p className="muted metadata">{temporary ? "Not saved" : conversationId ?? "New conversation"}</p>
      </aside>
      <section className="chat-panel">
        <header><div><p className="eyebrow">{temporary ? "TEMPORARY" : "CONVERSATION"}</p><h2>{messages.length === 0 ? "How can I help?" : appName}</h2></div>{streaming && <button className="secondary-button" onClick={() => abortController.current?.abort()} type="button">Stop</button>}</header>
        <div aria-live="polite" className="messages">
          {messages.length === 0 ? <div className="empty-state"><p>Ask anything. Configure a GPT-compatible provider in settings.</p></div> : messages.map((message) => <article className={"message message-" + message.role} key={message.id}><p className="message-role">{message.role}</p><div>{textFrom(message) || (message.role === "assistant" && streaming ? "Thinking…" : "")}</div></article>)}
        </div>
        {error !== undefined && <p className="error-message">{error}</p>}
        {queuedFollowUps.length > 0 && <section className="follow-up-queue"><p>Queued follow-ups</p>{queuedFollowUps.map((queued) => <div key={queued.id}><span>{queued.text || queued.files.length + " attachment(s)"}</span><button onClick={() => forceSendQueued({ id: queued.id })} type="button">Force send</button><button aria-label="Remove queued follow-up" onClick={() => setQueuedFollowUps((current) => current.filter((item) => item.id !== queued.id))} type="button">Remove</button></div>)}</section>}
        <form className="composer" onSubmit={submit} ref={composerForm}>
          <label className="attachment-button">Attach<input aria-label="Add attachments" multiple onChange={(event) => { void convertFileListToFileUIParts(event.target.files ?? undefined).then((nextFiles) => setFiles((current) => [...current, ...nextFiles])).catch(() => setError("Unable to prepare one or more attachments.")); event.target.value = ""; }} type="file" /></label>
          <textarea aria-label="Message" onChange={(event) => setDraft(event.target.value)} placeholder="Message…" rows={3} value={draft} />
          <button disabled={draft.trim() === "" && files.length === 0} type="submit">{streaming ? "Queue" : "Send"}</button>
        </form>
        {files.length > 0 && <div className="attachment-list">{files.map((file) => <button key={file.url} onClick={() => setFiles((current) => current.filter((item) => item.url !== file.url))} type="button">{file.filename ?? "Attachment"} ×</button>)}</div>}
      </section>
    </main>
  );
};
`;

export const webAppCss = (): string =>
  `:root { color: #e8eef6; background: #0b1020; font-family: Inter, ui-sans-serif, system-ui, sans-serif; } * { box-sizing: border-box; } body { margin: 0; min-width: 320px; } button, input, textarea { font: inherit; } button { cursor: pointer; } .chat-app { display: grid; grid-template-columns: 18rem minmax(0, 1fr); min-height: 100vh; } .settings-panel { display: flex; flex-direction: column; gap: 1rem; padding: 1.5rem; background: #111a31; border-right: 1px solid #273556; } .settings-panel h1, .chat-panel h2 { margin: 0; } label { display: grid; gap: .4rem; color: #bcc8dc; font-size: .85rem; } input, textarea { width: 100%; border: 1px solid #405174; border-radius: .55rem; padding: .65rem .75rem; color: #edf3ff; background: #0c1428; } .eyebrow { margin: 0 0 .35rem; color: #78a6ff; font-size: .72rem; font-weight: 700; letter-spacing: .11em; } .muted { color: #9dadc6; font-size: .9rem; } .metadata { overflow-wrap: anywhere; } .toggle { display: flex; align-items: center; gap: .55rem; } .toggle input { width: auto; } .conversation-list { display: grid; gap: .5rem; max-height: 16rem; overflow-y: auto; } .conversation { border: 1px solid #405174; border-radius: .55rem; padding: .45rem; } .conversation.active { border-color: #78a6ff; } .conversation > button { width: 100%; overflow: hidden; border: 0; padding: .35rem; color: inherit; background: transparent; text-align: left; text-overflow: ellipsis; white-space: nowrap; } .conversation-actions { display: flex; flex-wrap: wrap; gap: .25rem; } .conversation-actions button, .follow-up-queue button, .attachment-list button { border: 0; border-radius: .35rem; padding: .3rem .45rem; color: #dce9ff; background: #263858; font-size: .75rem; } .chat-panel { display: grid; grid-template-rows: auto minmax(0, 1fr) auto; min-height: 100vh; padding: 1.5rem clamp(1rem, 4vw, 4rem); background: radial-gradient(circle at 75% 0, #18274a, #0b1020 45%); } .chat-panel header { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding-bottom: 1rem; border-bottom: 1px solid #273556; } .messages { display: flex; flex-direction: column; gap: 1rem; overflow-y: auto; padding: 2rem 0; } .message { max-width: 52rem; padding: 1rem 1.15rem; border-radius: .75rem; line-height: 1.5; white-space: pre-wrap; } .message-user { align-self: flex-end; background: #2451a4; } .message-assistant { background: #17213a; } .message-role { margin: 0 0 .4rem; color: #a9c6ff; font-size: .72rem; font-weight: 700; text-transform: uppercase; } .empty-state { display: grid; place-items: center; flex: 1; color: #a8b7d0; text-align: center; } .composer { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; gap: .75rem; padding-top: 1rem; border-top: 1px solid #273556; } .composer textarea { resize: vertical; } .attachment-button { align-self: start; border: 1px solid #405174; border-radius: .55rem; padding: .65rem .75rem; color: #c8d7f1; cursor: pointer; } .attachment-button input { display: none; } .attachment-list { display: flex; flex-wrap: wrap; gap: .4rem; margin-top: .5rem; } .composer button, .secondary-button { border: 0; border-radius: .55rem; padding: .65rem 1rem; color: white; background: #3e78ef; } .secondary-button { background: #263858; } button:disabled { cursor: not-allowed; opacity: .5; } .error-message { margin: 0; color: #ffb4bd; } .follow-up-queue { display: grid; gap: .45rem; margin-bottom: .75rem; padding: .75rem; border: 1px solid #405174; border-radius: .55rem; background: #111a31; } .follow-up-queue p { margin: 0; color: #a9c6ff; font-size: .8rem; font-weight: 700; } .follow-up-queue div { display: flex; align-items: center; gap: .5rem; } .follow-up-queue span { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; } @media (max-width: 760px) { .chat-app { grid-template-columns: 1fr; } .settings-panel { border-right: 0; border-bottom: 1px solid #273556; } .chat-panel { min-height: 65vh; } }\n`;

export const webChatSettings = (): string => `import * as Option from "effect/Option";
import * as Schema from "effect/Schema";
import { defaultGenericChatSettings, GenericChatSettingsSchema, type GenericChatSettings } from "@emi/core/chat/settings";

export type ChatSettings = GenericChatSettings;

export const defaultChatSettings = defaultGenericChatSettings;

export const readChatSettings = ({ storageKey }: { storageKey: string }): ChatSettings => {
  const stored = localStorage.getItem(storageKey);
  if (stored === null) return defaultChatSettings;
  try {
    const decoded = Schema.decodeUnknownOption(Schema.fromJsonString(GenericChatSettingsSchema))(stored);
    if (Option.isNone(decoded)) return defaultChatSettings;
    return {
      ...defaultChatSettings,
      ...decoded.value,
      model: decoded.value.model || defaultChatSettings.model,
      titleModel: decoded.value.titleModel || defaultChatSettings.titleModel,
    };
  } catch {
    return defaultChatSettings;
  }
};
`;

export const webConversationClient = (): string => `import type { UIMessage } from "ai";
import * as Option from "effect/Option";
import * as Schema from "effect/Schema";
import { validateStoredUIMessages } from "@emi/core/chat/ui-messages";

const ConversationSchema = Schema.Struct({
  id: Schema.String,
  title: Schema.NullOr(Schema.String),
  status: Schema.Literals(["regular", "archived"]),
  pinned: Schema.Boolean,
  createdAt: Schema.String,
  updatedAt: Schema.String,
});

const ConversationListSchema = Schema.Struct({ conversations: Schema.Array(ConversationSchema) });
const ConversationMessageSchema = Schema.Struct({
  id: Schema.String,
  role: Schema.String,
  parts: Schema.String,
  model: Schema.NullOr(Schema.String),
  createdAt: Schema.String,
});
const ConversationDetailSchema = Schema.Struct({
  conversation: ConversationSchema,
  messages: Schema.Array(ConversationMessageSchema),
});

export type Conversation = typeof ConversationSchema.Type;

const apiUrl = (path: string): string => (import.meta.env.VITE_API_ORIGIN ?? "") + path;

const readResponse = async ({ response }: { response: Response }): Promise<unknown> => {
  const payload: unknown = await response.json();
  if (!response.ok) {
    const error = Schema.decodeUnknownOption(Schema.Struct({ error: Schema.String }))(payload);
    throw new Error(Option.isSome(error) ? error.value.error : "Request failed (" + response.status + ").");
  }
  return payload;
};

export const listConversations = async ({ search }: { search: string }): Promise<Conversation[]> => {
  const parameters = new URLSearchParams(search === "" ? {} : { search });
  const response = await fetch(apiUrl("/api/conversations?" + parameters.toString()));
  const payload = await readResponse({ response });
  const decoded = Schema.decodeUnknownSync(ConversationListSchema)(payload);
  return [...decoded.conversations];
};

export const loadConversation = async ({
  conversationId,
}: {
  conversationId: string;
}): Promise<{ conversation: Conversation; messages: UIMessage[] }> => {
  const response = await fetch(apiUrl("/api/conversations/" + conversationId));
  const payload = await readResponse({ response });
  const decoded = Schema.decodeUnknownSync(ConversationDetailSchema)(payload);
  const validated = await Promise.all(
    decoded.messages.map(async (message) => {
      if (message.role !== "user" && message.role !== "assistant" && message.role !== "system") return [];
      const parts = Schema.decodeUnknownOption(Schema.fromJsonString(Schema.Array(Schema.Unknown)))(message.parts);
      if (Option.isNone(parts)) return [];
      try {
        return await validateStoredUIMessages([{ id: message.id, role: message.role, parts: parts.value }]);
      } catch {
        return [];
      }
    }),
  );
  return { conversation: decoded.conversation, messages: validated.flat() };
};

export const updateConversation = async ({
  conversationId,
  patch,
}: {
  conversationId: string;
  patch: { title?: string; status?: "regular" | "archived"; pinned?: boolean };
}): Promise<Conversation> => {
  const response = await fetch(apiUrl("/api/conversations/" + conversationId), {
    method: "PATCH",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(patch),
  });
  const payload = await readResponse({ response });
  return Schema.decodeUnknownSync(Schema.Struct({ conversation: ConversationSchema }))(payload).conversation;
};

export const deleteConversation = async ({ conversationId }: { conversationId: string }): Promise<void> => {
  const response = await fetch(apiUrl("/api/conversations/" + conversationId), { method: "DELETE" });
  const payload = await readResponse({ response });
  Schema.decodeUnknownSync(Schema.Struct({ deleted: Schema.Literal(true) }))(payload);
};

export const cloneConversation = async ({ conversationId }: { conversationId: string }): Promise<Conversation> => {
  const response = await fetch(apiUrl("/api/conversations/" + conversationId + "/clone"), { method: "POST" });
  const payload = await readResponse({ response });
  return Schema.decodeUnknownSync(Schema.Struct({ conversation: ConversationSchema }))(payload).conversation;
};
`;

export const webMainTsx = (): string =>
  `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./app.tsx";

const container = document.getElementById("root");
if (container === null) throw new Error("Missing #root element");

createRoot(container).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;

export const workerPackageJson = (context: TemplateContext): string =>
  `{
  "name": "${workerPackageName(context)}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "deploy": "alchemy deploy",
    "destroy": "alchemy destroy",
    "dev": "alchemy dev",
    "db:check": "drizzle-kit check",
    "db:generate": "drizzle-kit generate",
    "dry": "alchemy deploy --dry-run",
    "typecheck": "tsc --noEmit",
    "format": "oxfmt --check",
    "format:fix": "oxfmt",
    "lint": "oxlint && oxfmt --check",
    "lint:fix": "oxlint --fix && oxfmt"
  },
  "dependencies": {
    "@emi/core": "${context.coreVersion}",
    "alchemy": "2.0.0-beta.59",
    "drizzle-orm": "0.45.2",
    "effect": "catalog:",
    "kysely": "0.29.3",
    "kysely-d1": "0.4.0"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "4.20250805.0",
    "@types/node": "^26.0.0",
    "drizzle-kit": "0.31.10",
    "miniflare": "4.20260710.0",
    "oxfmt": "catalog:",
    "oxlint": "catalog:",
    "typescript": "catalog:",
    "wrangler": "^4.111.0"
  }
}
`;

export const workerAlchemyRun = (context: TemplateContext): string =>
  `import * as Alchemy from "alchemy";
import * as Cloudflare from "alchemy/Cloudflare";
import * as Effect from "effect/Effect";

import AppWorkerLive, { AppWorker } from "./src/app.worker.ts";

export default Alchemy.Stack(
  "${context.slug}",
  {
    providers: Cloudflare.providers(),
    state: Cloudflare.state(),
  },
  Effect.gen(function* () {
    const db = yield* Cloudflare.D1.Database("AppData", {
      migrationsDir: "./migrations",
    });

    const worker = yield* AppWorker;

    return {
      url: worker.url.as<string>(),
      databaseId: db.databaseId,
    };
  }).pipe(Effect.provide(AppWorkerLive)),
);
`;

export const workerDrizzleConfig = (): string =>
  `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./migrations",
  migrations: {
    prefix: "timestamp",
  },
});
`;

export const workerTsconfig = (): string =>
  `{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext", "DOM"],
    "types": ["@cloudflare/workers-types", "node"],
    "module": "Preserve",
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "rewriteRelativeImportExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitThis": true,
    "isolatedModules": true
  },
  "include": ["alchemy.run.ts", "src/**/*.ts", "migrations/**/*.sql"]
}
`;

export const workerSchema = (): string =>
  `export {
  authAccount,
  authSession,
  authUser,
  authVerification,
  chatEvents,
  chatGenerationChunks,
  chatGenerations,
  conversations,
  messages,
  suggestions,
  threadMessages,
  threads,
  type AuthDatabaseSchema,
  type ConversationDatabaseSchema,
} from "@emi/core/server";

import type { AuthDatabaseSchema, ConversationDatabaseSchema } from "@emi/core/server";

export type AppDatabaseSchema = ConversationDatabaseSchema & AuthDatabaseSchema;
`;

export const workerAppWorker = (context: TemplateContext): string =>
  `import * as Cloudflare from "alchemy/Cloudflare";
import { RuntimeContext } from "alchemy";
import { Stack } from "alchemy/Stack";
import * as Config from "effect/Config";
import * as Effect from "effect/Effect";
import { HttpServerRequest } from "effect/unstable/http/HttpServerRequest";
import * as HttpRouter from "effect/unstable/http/HttpRouter";
import * as HttpServerResponse from "effect/unstable/http/HttpServerResponse";
import {
  authenticateWorkerFetch,
  makeGenericChatRoutes,
  makeQueryDatabaseClient,
  type CloudflareQueryDatabaseClient,
} from "@emi/core/cloudflare";
import {
  isGenericProtectedPath,
  type AuthDatabaseSchema,
  type ConversationDatabaseSchema,
} from "@emi/core/server";

const DB = Cloudflare.D1.Database("AppData");

type AppDatabaseSchema = ConversationDatabaseSchema & AuthDatabaseSchema;

export class AppWorker extends Cloudflare.Worker<AppWorker, {}>()("AppWorker") {}

export default AppWorker.make(
  Stack.useSync(() => ({
    main: import.meta.url,
    compatibility: { flags: ["nodejs_compat"] },
    env: {
      BETTER_AUTH_SECRET: Config.redacted("BETTER_AUTH_SECRET"),
      BETTER_AUTH_URL: Config.redacted("BETTER_AUTH_URL"),
      AUTH_APP_NAME: Config.string("AUTH_APP_NAME").pipe(
        Config.withDefault(${JSON.stringify(context.appName)}),
      ),
      ALLOW_DEMO_USER_HEADER: Config.string("ALLOW_DEMO_USER_HEADER").pipe(
        Config.withDefault("0"),
      ),
    },
    observability: { enabled: true },
  })),
  Effect.gen(function* () {
    const query = yield* Cloudflare.D1.QueryDatabase(DB);
    const db = makeQueryDatabaseClient<AppDatabaseSchema>({ query });
    const env: Record<string, unknown> = yield* Cloudflare.Workers.WorkerEnvironment;
    const router = yield* HttpRouter.make;
    const routes = makeGenericChatRoutes({
      db: db as unknown as CloudflareQueryDatabaseClient<ConversationDatabaseSchema>,
    });
    yield* Effect.gen(function* () {
      yield* router.add("GET", "/api/health", () =>
        HttpServerResponse.json({
          name: ${JSON.stringify(context.appName)},
        }),
      );
      yield* router.add("GET", "/api/conversations", routes.conversations);
      yield* router.add("POST", "/api/conversations", routes.conversations);
      yield* router.add("GET", "/api/conversations/:conversationId", routes.conversation);
      yield* router.add("PATCH", "/api/conversations/:conversationId", routes.conversation);
      yield* router.add("DELETE", "/api/conversations/:conversationId", routes.conversation);
      yield* router.add("POST", "/api/conversations/:conversationId/clone", routes.clone);
      yield* router.add("GET", "/api/conversations/:conversationId/threads", routes.threads);
      yield* router.add("POST", "/api/conversations/:conversationId/threads", routes.threads);
      yield* router.add("GET", "/api/conversations/:conversationId/threads/:threadId", routes.thread);
      yield* router.add("PATCH", "/api/conversations/:conversationId/threads/:threadId", routes.thread);
      yield* router.add("DELETE", "/api/conversations/:conversationId/threads/:threadId", routes.thread);
      yield* router.add("POST", "/api/chat", routes.chat);
      yield* router.add("GET", "/api/chat/:conversationId/stream", () =>
        Effect.gen(function* () {
          const params = yield* HttpRouter.params;
          return yield* routes.resume({ conversationId: params.conversationId ?? "" })();
        }),
      );
      yield* router.add("*", "/*", () =>
        Effect.succeed(HttpServerResponse.text("Not Found", { status: 404 })),
      );
    }) as Effect.Effect<void>;

    return {
      fetch: Effect.gen(function* () {
        const request = yield* HttpServerRequest;
        return yield* authenticateWorkerFetch({
          db,
          environment: env,
          isProtectedPath: isGenericProtectedPath,
          policy: "anonymous",
          request,
          route: router.asHttpEffect(),
        });
      }).pipe(
        Effect.scoped,
        Effect.catch((error) =>
          Effect.logError("Unhandled fetch error").pipe(
            Effect.annotateLogs({ error: String(error) }),
            Effect.as(HttpServerResponse.text("Internal Server Error", { status: 500 })),
          ),
        ),
        Effect.provide(RuntimeContext.phantom),
      ),
    };
  }).pipe(Effect.provide(Cloudflare.D1.QueryDatabaseBinding)),
);
`;
