export interface TemplateContext {
  appName: string;
  slug: string;
  coreVersion: string;
  distributionMode: "dependency" | "owned";
}

const webPackageName = (context: TemplateContext): string => context.slug + "-web";
const workerPackageName = (context: TemplateContext): string => context.slug + "-worker";
const coreDependency = (context: TemplateContext): string =>
  context.distributionMode === "owned" ? "workspace:*" : context.coreVersion;
const lines = (values: string[]): string => values.join("\n") + "\n";

export const readme = (context: TemplateContext): string =>
  lines([
    "# " + context.appName,
    "",
    "A ChatGPT-like application generated by @emi/create-chat-app. The generated project owns its",
    "generic web, Worker, and reusable core source, copied from canonical fixtures. Everything is",
    "local and yours to edit.",
    "",
    "## Layout",
    "",
    "web/       Vite + React generic chat application",
    "worker/    Alchemy Cloudflare Worker plus Drizzle schema",
    "",
    "## Getting started",
    "",
    "pnpm install",
    "pnpm typecheck",
    "pnpm --dir worker db:generate",
    "pnpm --dir worker dev",
    "pnpm --dir web dev",
    "pnpm --dir web test:api",
    "pnpm --dir web test:e2e:install",
    "pnpm --dir web test:e2e",
    "",
    "The web dev server proxies /api to the Worker on http://127.0.0.1:8787.",
    "",
    "Only web/src/app-config.ts and worker/src/app-config.ts are generated source configuration.",
    "Every other application file matches generic fixtures and is yours to edit.",
    "",
    "## Deferred",
    "",
    context.distributionMode === "owned"
      ? "Use --mode dependency only when your existing workspace or a published package supplies @emi/core."
      : "This dependency-mode app expects @emi/core version " + context.coreVersion + ".",
  ]);

export const workspacePackageJson = (context: TemplateContext): string =>
  JSON.stringify(
    {
      name: context.slug,
      version: "0.1.0",
      private: true,
      type: "module",
      packageManager: "pnpm@11.0.0",
      scripts: {
        build: "pnpm --dir web build",
        typecheck: "pnpm -r typecheck",
        check: "pnpm typecheck && pnpm --dir worker db:check && pnpm build",
      },
    },
    undefined,
    2,
  ) + "\n";

export const workspaceConfig = (): string =>
  lines([
    "packages:",
    '  - "core"',
    '  - "web"',
    '  - "worker"',
    "catalog:",
    '  "@ai-sdk/openai": "4.0.30"',
    '  "@cloudflare/workers-types": "5.20260804.1"',
    '  "@effect/platform-node": "4.0.0-beta.88"',
    '  "@playwright/test": "1.62.1"',
    '  "playwright-bdd": "9.2.0"',
    '  "@tailwindcss/postcss": "4.3.3"',
    '  "@types/json-schema": "7.0.15"',
    '  "@types/node": "26.1.2"',
    '  "@types/react": "19.2.18"',
    '  "@types/react-dom": "19.2.4"',
    '  "@testing-library/jest-dom": "7.0.0"',
    '  "@testing-library/react": "16.3.2"',
    '  "@testing-library/user-event": "14.6.3"',
    '  "@vitejs/plugin-react": "6.0.5"',
    '  "@vitest/coverage-v8": "4.1.10"',
    '  ai: "7.0.52"',
    '  alchemy: "2.0.0-beta.59"',
    '  effect: "4.0.0-beta.88"',
    '  better-auth: "1.6.26"',
    '  class-variance-authority: "0.7.1"',
    '  clsx: "2.1.1"',
    '  drizzle-kit: "0.31.10"',
    '  drizzle-orm: "0.45.2"',
    '  esbuild: "0.28.1"',
    '  jsdom: "30.0.1"',
    '  kysely: "0.29.4"',
    '  kysely-d1: "0.4.0"',
    '  lucide-react: "1.28.0"',
    '  miniflare: "4.20260730.0"',
    '  oxfmt: "0.62.0"',
    '  oxlint: "1.77.0"',
    '  radix-ui: "1.6.7"',
    '  react: "19.2.8"',
    '  react-dom: "19.2.8"',
    '  react-markdown: "10.1.0"',
    '  remark-gfm: "4.0.1"',
    '  tailwind-merge: "3.6.0"',
    '  tailwindcss: "4.3.3"',
    '  tw-animate-css: "1.4.0"',
    '  typescript: "7.0.2"',
    '  vite: "8.2.0"',
    '  vitest: "4.1.10"',
    '  wrangler: "4.118.0"',
    '  xstate: "5.32.5"',
    "overrides:",
    '  "better-auth>next": "-"',
    "allowBuilds:",
    "  esbuild: true",
    "  msgpackr-extract: true",
    "  sharp: true",
    "  workerd: true",
    "onlyBuiltDependencies: [msgpackr-extract, workerd]",
    'trustPolicy: "off"',
  ]);

export const workspaceFormatConfig = (): string =>
  JSON.stringify(
    {
      ignorePatterns: ["**/migrations/meta/**"],
    },
    undefined,
    2,
  ) + "\n";

export const envExample = (): string =>
  lines([
    "# Copy to .env and fill in secrets for session auth.",
    "# Required for the worker:",
    "#   BETTER_AUTH_SECRET   (min 32 chars)",
    "#   BETTER_AUTH_URL      (public origin, e.g. http://localhost:3233)",
    "# Optional local debugging only (never in production):",
    "#   ALLOW_DEMO_USER_HEADER=1   then send x-demo-user-id on API calls",
    "# Optional branding:",
    "#   AUTH_APP_NAME=Core Chat",
  ]);

export const gitignore = (): string =>
  lines([
    "node_modules",
    "dist",
    ".alchemy",
    ".wrangler",
    "data",
    ".env",
    ".env.*",
    "!.env.example",
  ]);

export const webPackageJson = (context: TemplateContext): string =>
  JSON.stringify(
    {
      name: webPackageName(context),
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "vite --port 3233",
        build: "vite build",
        typecheck: "tsc --noEmit",
        start: "vite preview --port 3233",
        test: "vitest run --exclude test/api.integration.test.ts",
        "test:api": "vitest run --config vitest.integration.config.ts",
        "test:e2e": "bddgen && playwright test",
        "test:e2e:install": "playwright install chromium",
        format: "oxfmt --check",
        "format:fix": "oxfmt",
        lint: "oxlint && oxfmt --check",
        "lint:fix": "oxlint --fix && oxfmt",
      },
      dependencies: {
        "@emi/core": coreDependency(context),
        "better-auth": "catalog:",
        "class-variance-authority": "catalog:",
        clsx: "catalog:",
        effect: "catalog:",
        "lucide-react": "catalog:",
        "radix-ui": "catalog:",
        react: "catalog:",
        "react-dom": "catalog:",
        "tailwind-merge": "catalog:",
        "tw-animate-css": "catalog:",
      },
      devDependencies: {
        "@playwright/test": "catalog:",
        "@tailwindcss/postcss": "catalog:",
        "@types/node": "catalog:",
        "@types/react": "catalog:",
        "@types/react-dom": "catalog:",
        "@vitejs/plugin-react": "catalog:",
        oxfmt: "catalog:",
        oxlint: "catalog:",
        "playwright-bdd": "catalog:",
        tailwindcss: "catalog:",
        typescript: "catalog:",
        vite: "catalog:",
        vitest: "catalog:",
      },
    },
    undefined,
    2,
  ) + "\n";

export const webIndexHtml = (context: TemplateContext): string =>
  lines([
    "<!doctype html>",
    '<html lang="en">',
    "  <head>",
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '    <meta name="theme-color" content="#ffffff" />',
    '    <link rel="manifest" href="/manifest.webmanifest" />',
    "    <title>" + context.appName + "</title>",
    "  </head>",
    "  <body>",
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.tsx"></script>',
    "  </body>",
    "</html>",
  ]);

export const webManifest = (context: TemplateContext): string =>
  JSON.stringify(
    {
      name: context.appName,
      short_name: context.appName,
      start_url: "/",
      display: "standalone",
      background_color: "#ffffff",
      theme_color: "#ffffff",
      icons: [{ src: "/icon.svg", sizes: "any", type: "image/svg+xml" }],
    },
    undefined,
    2,
  ) + "\n";

export const webAppConfig = (context: TemplateContext): string =>
  lines([
    'import type { ChatAppConfig } from "@emi/core/chat";',
    "",
    "export const genericChatAppConfig = {",
    "  name: " + JSON.stringify(context.appName) + ",",
    '  settingsStorageKey: "emi-core-chat-settings",',
    '  version: "0.1.0",',
    '  releaseNotes: ["Generic chat foundations are ready for application-specific extensions."],',
    "} satisfies ChatAppConfig;",
  ]);

export const workerPackageJson = (context: TemplateContext): string =>
  JSON.stringify(
    {
      name: workerPackageName(context),
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        deploy: "alchemy deploy",
        destroy: "alchemy destroy",
        dev: "alchemy dev",
        "db:check": "drizzle-kit check",
        "db:generate": "drizzle-kit generate",
        dry: "alchemy deploy --dry-run",
        typecheck: "tsc --noEmit",
        format: "oxfmt --check",
        "format:fix": "oxfmt",
        lint: "oxlint && oxfmt --check",
        "lint:fix": "oxlint --fix && oxfmt",
      },
      dependencies: {
        "@emi/core": coreDependency(context),
        ...(context.distributionMode === "owned" ? { "@emi/core": "workspace:*" } : {}),
        alchemy: "catalog:",
        "drizzle-orm": "catalog:",
        effect: "catalog:",
        kysely: "catalog:",
        "kysely-d1": "catalog:",
      },
      devDependencies: {
        "@cloudflare/workers-types": "catalog:",
        "@effect/platform-node": "catalog:",
        "@types/node": "catalog:",
        "drizzle-kit": "catalog:",
        miniflare: "catalog:",
        oxfmt: "catalog:",
        oxlint: "catalog:",
        typescript: "catalog:",
        wrangler: "catalog:",
      },
    },
    undefined,
    2,
  ) + "\n";

export const workerAppConfig = (context: TemplateContext): string =>
  lines([
    'import type { ChatAppConfig } from "@emi/core/chat";',
    "",
    "export const genericWorkerAppConfig = {",
    "  name: " + JSON.stringify(context.appName) + ",",
    '  databaseName: "AppData",',
    '  settingsStorageKey: "emi-core-chat-settings",',
    '  version: "0.1.0",',
    '  releaseNotes: ["Generic chat foundations are ready for application-specific extensions."],',
    "} satisfies ChatAppConfig & { databaseName: string };",
  ]);
