export interface TemplateContext {
  appName: string;
  slug: string;
  coreVersion: string;
}

const webPackageName = (context: TemplateContext): string => `${context.slug}-web`;
const workerPackageName = (context: TemplateContext): string => `${context.slug}-worker`;

export const readme = (context: TemplateContext): string =>
  `# ${context.appName}

A thin composition root generated by \`@emi/create-chat-app\`. Application logic — conversations,
messages, branches, resumable generation, memory, notes, and the chat shell UI — lives entirely in
released/workspace core packages:

- \`@emi/core/contract\` — schemas and API contracts
- \`@emi/core/server\` — auth, conversations, branches, generation, memory, notes
- \`@emi/core/web\` — chat shell, composer, sidebar, settings
- \`@emi/core/cloudflare\` — D1, R2, Durable Object, Worker, and Alchemy adapters

Nothing under \`web/\` or \`worker/\` in this generated tree is a copy of core package source. Both
sub-packages only import the packages above by name (currently pinned to \`${context.coreVersion}\`).
Upgrading is a normal dependency bump in \`web/package.json\` and \`worker/package.json\`, not a manual
port.

## Layout

\`\`\`text
web/       Vite + React composition root depending on @emi/core/web + @emi/core/contract
worker/    Alchemy Cloudflare Worker composition root depending on @emi/core/server + @emi/core/cloudflare
\`\`\`

## Getting started

Add \`web\` and \`worker\` to a pnpm workspace that also resolves the \`@emi/core\` packages (this
repository's root workspace already does, if this directory was generated under \`apps/\`). Then:

\`\`\`bash
pnpm install
pnpm --filter ${webPackageName(context)} typecheck
pnpm --filter ${workerPackageName(context)} typecheck
pnpm --filter ${workerPackageName(context)} db:generate
pnpm --filter ${webPackageName(context)} dev
pnpm --filter ${workerPackageName(context)} dev
\`\`\`

A product flavor adds nav, pages, tools, and prompt fragments by passing \`CoreWebContributions\` to
\`CoreWebProvider\` (web) and by merging an \`AppDefinition\` with \`coreAppDefinition\` (worker) — see
\`apps/generic-web\` and \`apps/generic-worker\` in the upstream monorepo for a worked example.

## Deferred

Real npm publishing of the \`@emi/core\` package is deferred; until then, the generated
dependency version (\`${context.coreVersion}\`) only resolves inside a pnpm workspace that also
contains that package as a member.
`;

export const envExample = (): string =>
  `# Copy to .env and fill in secrets once your flavor requires authentication or a model provider key.
# The generated worker composition root does not require any secrets by default; it uses a demo
# \`x-demo-user-id\` header instead of session auth (see worker/src/app.worker.ts).
`;

export const gitignore = (): string =>
  `node_modules
dist
.alchemy
.wrangler
data
.env
.env.*
!.env.example
`;

export const webPackageJson = (context: TemplateContext): string =>
  `{
  "name": "${webPackageName(context)}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --port 3233",
    "build": "vite build",
    "typecheck": "tsc --noEmit",
    "start": "vite preview --port 3233",
    "format": "oxfmt --check",
    "format:fix": "oxfmt",
    "lint": "oxlint && oxfmt --check",
    "lint:fix": "oxlint --fix && oxfmt"
  },
  "dependencies": {
    "@emi/core": "${context.coreVersion}",
    "react": "^19.2.7",
    "react-dom": "^19.2.7"
  },
  "devDependencies": {
    "@types/node": "^26.0.0",
    "@types/react": "^19.2.17",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^6.0.3",
    "oxfmt": "catalog:",
    "oxlint": "catalog:",
    "typescript": "catalog:",
    "vite": "^8.1.4"
  }
}
`;

export const webIndexHtml = (context: TemplateContext): string =>
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${context.appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

export const webViteEnvDts = (): string => `/// <reference types="vite/client" />\n`;

export const webViteConfig = (): string =>
  `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: "dist",
  },
});
`;

export const webTsconfig = (): string =>
  `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "types": ["node"]
  },
  "include": ["vite-env.d.ts", "src/**/*.ts", "src/**/*.tsx"],
  "exclude": ["node_modules"]
}
`;

export const webAppTsx = (context: TemplateContext): string =>
  `import { ChatShell, CoreWebProvider, type CoreWebContributions } from "@emi/core/web";

/**
 * Empty contributions prove \`@emi/core/web\` renders a usable shell with no
 * product flavor registered. A real flavor adds nav, pages, and tool
 * renderers through this same \`CoreWebContributions\` shape.
 */
const contributions: CoreWebContributions = {
  nav: [{ id: "home", label: "Home", href: "/" }],
};

export const App = () => (
  <CoreWebProvider contributions={contributions}>
    <ChatShell title="${context.appName}">
      <main style={{ padding: "2rem" }}>
        <h1>${context.appName}</h1>
        <p>
          This composition root depends only on <code>@emi/core/web</code> and{" "}
          <code>@emi/core/contract</code> — no copied core source.
        </p>
      </main>
    </ChatShell>
  </CoreWebProvider>
);
`;

export const webMainTsx = (): string =>
  `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { App } from "./app.tsx";

const container = document.getElementById("root");
if (container === null) throw new Error("Missing #root element");

createRoot(container).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;

export const workerPackageJson = (context: TemplateContext): string =>
  `{
  "name": "${workerPackageName(context)}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "deploy": "alchemy deploy",
    "destroy": "alchemy destroy",
    "dev": "alchemy dev",
    "db:check": "drizzle-kit check",
    "db:generate": "drizzle-kit generate",
    "dry": "alchemy deploy --dry-run",
    "typecheck": "tsc --noEmit",
    "format": "oxfmt --check",
    "format:fix": "oxfmt",
    "lint": "oxlint && oxfmt --check",
    "lint:fix": "oxlint --fix && oxfmt"
  },
  "dependencies": {
    "@emi/core": "${context.coreVersion}",
    "alchemy": "2.0.0-beta.59",
    "drizzle-orm": "0.45.2",
    "effect": "catalog:",
    "kysely": "0.29.3",
    "kysely-d1": "0.4.0"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "4.20250805.0",
    "@types/node": "^26.0.0",
    "drizzle-kit": "0.31.10",
    "miniflare": "4.20260710.0",
    "oxfmt": "catalog:",
    "oxlint": "catalog:",
    "typescript": "catalog:",
    "wrangler": "^4.111.0"
  }
}
`;

export const workerAlchemyRun = (context: TemplateContext): string =>
  `import * as Alchemy from "alchemy";
import * as Cloudflare from "alchemy/Cloudflare";
import * as Effect from "effect/Effect";

import AppWorkerLive, { AppWorker } from "./src/app.worker.ts";

export default Alchemy.Stack(
  "${context.slug}",
  {
    providers: Cloudflare.providers(),
    state: Cloudflare.state(),
  },
  Effect.gen(function* () {
    const db = yield* Cloudflare.D1.Database("AppData", {
      migrationsDir: "./migrations",
    });

    const worker = yield* AppWorker;

    return {
      url: worker.url.as<string>(),
      databaseId: db.databaseId,
    };
  }).pipe(Effect.provide(AppWorkerLive)),
);
`;

export const workerDrizzleConfig = (): string =>
  `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./migrations",
  migrations: {
    prefix: "timestamp",
  },
});
`;

export const workerTsconfig = (): string =>
  `{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext", "DOM"],
    "types": ["@cloudflare/workers-types", "node"],
    "module": "Preserve",
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "rewriteRelativeImportExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,
    "strict": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitThis": true,
    "isolatedModules": true
  },
  "include": ["alchemy.run.ts", "src/**/*.ts", "migrations/**/*.sql"]
}
`;

export const workerSchema = (): string =>
  `export {
  conversations,
  messages,
  suggestions,
  threadMessages,
  threads,
  type ConversationDatabaseSchema,
} from "@emi/core/server";
`;

export const workerAppWorker = (context: TemplateContext): string =>
  `import * as Cloudflare from "alchemy/Cloudflare";
import { RuntimeContext } from "alchemy";
import { Stack } from "alchemy/Stack";
import * as Effect from "effect/Effect";
import { HttpServerRequest } from "effect/unstable/http/HttpServerRequest";
import * as HttpRouter from "effect/unstable/http/HttpRouter";
import * as HttpServerResponse from "effect/unstable/http/HttpServerResponse";
import {
  coreAppDefinition,
  makeConversationStore,
  makeRequestContext,
  type ConversationDatabaseSchema,
} from "@emi/core/server";
import {
  makeQueryDatabaseClient,
  type CloudflareQueryDatabaseClient,
} from "@emi/core/cloudflare";

const DB = Cloudflare.D1.Database("AppData");

/**
 * \`x-demo-user-id\` is a placeholder identity for this scaffold. It proves the
 * core conversation store and D1 adapter compose end to end without pulling
 * in any flavor. Real deployments must replace it with session-based auth
 * before exposing "${context.appName}" publicly.
 */
const demoUserId = (request: HttpServerRequest): string | undefined =>
  request.headers["x-demo-user-id"];

const conversationsRoute = (db: CloudflareQueryDatabaseClient<ConversationDatabaseSchema>) =>
  Effect.fn("app.conversations")(function* (request: HttpServerRequest) {
    const userId = demoUserId(request);
    if (userId === undefined || userId === "") {
      return yield* HttpServerResponse.json(
        { error: "Missing x-demo-user-id header (demo identity only, not production auth)" },
        { status: 401 },
      );
    }
    const store = makeConversationStore({ db, requestContext: makeRequestContext({ userId }) });
    if (request.method === "POST") {
      const id = yield* store.create();
      return yield* HttpServerResponse.json({ id }, { status: 201 });
    }
    const conversations = yield* store.list();
    return yield* HttpServerResponse.json({ conversations });
  });

export class AppWorker extends Cloudflare.Worker<AppWorker, {}>()("AppWorker") {}

export default AppWorker.make(
  Stack.useSync(() => ({
    main: import.meta.url,
    compatibility: { flags: ["nodejs_compat"] },
    observability: { enabled: true },
  })),
  Effect.gen(function* () {
    const query = yield* Cloudflare.D1.QueryDatabase(DB);
    const db = makeQueryDatabaseClient<ConversationDatabaseSchema>({ query });

    const router = yield* HttpRouter.make;
    yield* Effect.gen(function* () {
      yield* router.add("GET", "/api/health", () =>
        HttpServerResponse.json({
          name: coreAppDefinition.identity.name,
          description: coreAppDefinition.identity.description,
        }),
      );
      yield* router.add("GET", "/api/conversations", conversationsRoute(db));
      yield* router.add("POST", "/api/conversations", conversationsRoute(db));
      yield* router.add("*", "/*", () =>
        Effect.succeed(HttpServerResponse.text("Not Found", { status: 404 })),
      );
    }) as Effect.Effect<void>;

    return {
      fetch: router.asHttpEffect().pipe(
        Effect.scoped,
        Effect.catch((error) =>
          Effect.logError("Unhandled fetch error").pipe(
            Effect.annotateLogs({ error: String(error) }),
            Effect.as(HttpServerResponse.text("Internal Server Error", { status: 500 })),
          ),
        ),
        Effect.provide(RuntimeContext.phantom),
      ),
    };
  }).pipe(Effect.provide(Cloudflare.D1.QueryDatabaseBinding)),
);
`;
