import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it } from "vitest";

const generated = readFileSync(
  join(
    dirname(fileURLToPath(import.meta.url)),
    "../src/integrations/hevy/generated/hevy-api.generated.ts",
  ),
  "utf8",
);

describe("Hevy typed-openapi client runtime", () => {
  it("stays types-only until typed-openapi Effect runtime is published", () => {
    assert.match(generated, /AUTO-GENERATED by typed-openapi/);
    assert.match(generated, /TODO: regenerate with `typed-openapi --runtime effect`/);
    assert.doesNotMatch(generated, /from ["']effect\/Schema["']/);
  });
});
