import type {
  Attachment,
  DynamicComponentElement,
  DynamicComponentEnvelope,
  DynamicComponentSpec,
  ExtensionPart,
  FileMessagePart,
  MessagePart,
  ReasoningMessagePart,
  TextMessagePart,
  ToolCall,
  ToolCallMessagePart,
  ToolResult,
  ToolResultMessagePart,
  ToolInvocationMessagePart,
} from "./protocol/parts.ts";
import type {
  ChatMessage,
  ChatMessageDto,
  MessageRole,
  MessageUsage,
} from "./protocol/messages.ts";
import type {
  Conversation,
  ConversationDto,
  Memory,
  MemoryDto,
  MemorySummary,
  MemorySummaryDto,
  Thread,
  ThreadDto,
} from "./protocol/resources.ts";
import type {
  AttachmentId,
  GenerationId,
  MemoryId,
  MessageId,
  ToolCallId,
  ThreadId,
  Timestamp,
} from "./protocol/ids.ts";
import type {
  GenerationEvent,
  ModelCapabilities,
  ModelConfiguration,
  ModelDescriptor,
  ModelGenerationInput,
  ModelProvider,
  ModelProviderError,
} from "./protocol/model.ts";
import type { TransportError } from "./protocol/errors.ts";
import { ProtocolDecodeError } from "./protocol/errors.ts";
import { ChatProtocol } from "./protocol/mappers.ts";
import type { ProtocolEffect, ProtocolSchemas } from "./protocol/mappers.ts";

export type {
  Attachment,
  AttachmentId,
  ChatMessage,
  ChatMessageDto,
  Conversation,
  ConversationDto,
  ExtensionPart,
  DynamicComponentElement,
  DynamicComponentEnvelope,
  DynamicComponentSpec,
  FileMessagePart,
  GenerationEvent,
  GenerationId,
  Memory,
  MemoryDto,
  MemorySummary,
  MemorySummaryDto,
  MemoryId,
  MessageId,
  MessagePart,
  MessageRole,
  MessageUsage,
  ModelCapabilities,
  ModelConfiguration,
  ModelDescriptor,
  ModelGenerationInput,
  ModelProvider,
  ModelProviderError,
  ReasoningMessagePart,
  TextMessagePart,
  Thread,
  ThreadDto,
  ThreadId,
  Timestamp,
  ToolCall,
  ToolCallId,
  ToolCallMessagePart,
  ToolResult,
  ToolResultMessagePart,
  ToolInvocationMessagePart,
  TransportError,
  ProtocolEffect,
  ProtocolSchemas,
};

export { ChatProtocol, ProtocolDecodeError };
