import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const BANNER = `/**
 * AUTO-GENERATED by typed-openapi — do not edit by hand.
 *
 * Regen: \`pnpm --filter @emi/flavor-healthfit hevy:client\`
 *
 * TODO: regenerate with \`typed-openapi --runtime effect\` once Effect Schema
 * runtime is published (see typedapi plans/effect-schema-runtime.md).
 */

`;

const main = async () => {
  const scriptDirectory = dirname(fileURLToPath(import.meta.url));
  const packageRoot = resolve(scriptDirectory, "..");
  const openApiPath = "src/integrations/hevy/openapi/hevy.openapi.json";
  const outputPath = resolve(packageRoot, "src/integrations/hevy/generated/hevy-api.generated.ts");

  const generate = spawnSync(
    "pnpm",
    [
      "exec",
      "typed-openapi",
      openApiPath,
      "-o",
      "src/integrations/hevy/generated/hevy-api.generated.ts",
      "--runtime",
      "none",
      "--format",
    ],
    {
      cwd: packageRoot,
      stdio: "inherit",
      shell: false,
    },
  );

  if (generate.status !== 0) {
    throw new Error(`typed-openapi exited with status ${String(generate.status)}`);
  }

  const generated = await readFile(outputPath, "utf8");
  const withoutExistingBanner = generated.replace(/^\/\*\*[\s\S]*?\*\/\s*/, (match) =>
    match.includes("AUTO-GENERATED by typed-openapi") ? "" : match,
  );

  const stripCompatible = withoutExistingBanner.replace(
    /export class ApiClient \{\n  baseUrl: string = "";\n  successStatusCodes = successStatusCodes;\n  errorStatusCodes = errorStatusCodes;\n  validate: ValidateSide = "none";\n  onValidate\?: OnValidate;\n\n  constructor\(\n    public fetcher: Fetcher,\n    options\?: \{ validate\?: ValidateSide; onValidate\?: OnValidate \},\n  \) \{\n    if \(options\?\.validate !== undefined\) this\.validate = options\.validate;\n    if \(options\?\.onValidate\) this\.onValidate = options\.onValidate;\n  \}\n/,
    `export class ApiClient {
  baseUrl: string = "";
  successStatusCodes = successStatusCodes;
  errorStatusCodes = errorStatusCodes;
  validate: ValidateSide = "none";
  onValidate?: OnValidate;
  fetcher: Fetcher;

  constructor(
    fetcher: Fetcher,
    options?: { validate?: ValidateSide; onValidate?: OnValidate },
  ) {
    this.fetcher = fetcher;
    if (options?.validate !== undefined) this.validate = options.validate;
    if (options?.onValidate) this.onValidate = options.onValidate;
  }
`,
  );

  if (stripCompatible === withoutExistingBanner) {
    throw new Error("Failed to rewrite ApiClient constructor for strip-types compatibility");
  }

  await writeFile(outputPath, `${BANNER}${stripCompatible}`, "utf8");
  const format = spawnSync("pnpm", ["exec", "oxfmt", outputPath], {
    cwd: packageRoot,
    stdio: "inherit",
    shell: false,
  });
  if (format.status !== 0) {
    throw new Error(`oxfmt exited with status ${String(format.status)}`);
  }
  console.log(`Wrote ${outputPath}`);
};

await main();
